### ISSUE TITLE
using bepasty-cli results in "TypeError: a bytes-like object is required, not 'str'"

### ISSUE THREAD

**Issue by Lassulus** [bepasty/bepasty-server#200]
Server runs on NixOS 19.03 with python 3.7 for bepasty.
when uploading anything with bepasty-cli the cli reports an 500 error and the server logs this stacktrace:
```
Apr 13 19:14:03 prism gunicorn[28360]: Traceback (most recent call last):
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/gn2wii76cawigjyilhxhd98qlc9fqv2z-python3-3.7.3-env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
Apr 13 19:14:03 prism gunicorn[28360]:     response = self.full_dispatch_request()
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/gn2wii76cawigjyilhxhd98qlc9fqv2z-python3-3.7.3-env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
Apr 13 19:14:03 prism gunicorn[28360]:     rv = self.handle_user_exception(e)
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/gn2wii76cawigjyilhxhd98qlc9fqv2z-python3-3.7.3-env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
Apr 13 19:14:03 prism gunicorn[28360]:     reraise(exc_type, exc_value, tb)
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/gn2wii76cawigjyilhxhd98qlc9fqv2z-python3-3.7.3-env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
Apr 13 19:14:03 prism gunicorn[28360]:     raise value
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/gn2wii76cawigjyilhxhd98qlc9fqv2z-python3-3.7.3-env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
Apr 13 19:14:03 prism gunicorn[28360]:     rv = self.dispatch_request()
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/gn2wii76cawigjyilhxhd98qlc9fqv2z-python3-3.7.3-env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
Apr 13 19:14:03 prism gunicorn[28360]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/gn2wii76cawigjyilhxhd98qlc9fqv2z-python3-3.7.3-env/lib/python3.7/site-packages/flask/views.py", line 88, in view
Apr 13 19:14:03 prism gunicorn[28360]:     return self.dispatch_request(*args, **kwargs)
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/gn2wii76cawigjyilhxhd98qlc9fqv2z-python3-3.7.3-env/lib/python3.7/site-packages/flask/views.py", line 158, in dispatch_request
Apr 13 19:14:03 prism gunicorn[28360]:     return meth(*args, **kwargs)
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/gn2wii76cawigjyilhxhd98qlc9fqv2z-python3-3.7.3-env/lib/python3.7/site-packages/bepasty/apis/rest.py", line 96, in post
Apr 13 19:14:03 prism gunicorn[28360]:     response.headers["transaction-id"] = base64.b64encode(name)
Apr 13 19:14:03 prism gunicorn[28360]:   File "/nix/store/0n8slcq8p5x31kc9hncabsqq9y3fpkzp-python3-3.7.3/lib/python3.7/base64.py", line 58, in b64encode
Apr 13 19:14:03 prism gunicorn[28360]:     encoded = binascii.b2a_base64(s, newline=False)
Apr 13 19:14:03 prism gunicorn[28360]: TypeError: a bytes-like object is required, not 'str'
```

This was also reproduced with Python 3.5 and 3.6. Does not happen in Python 2.7

**Comment by ThomasWaldmann** [comment]
py37: the b64(en|de)code calls get and return `bytes`, not `str`.
py27: ... get and return `str`, not `unicode` (so, "bytes" here also).

```
bytes = b64encode(bytes, altchars=None)
bytes = b64decode(bytes, altchars=None, validate=False)
```

**Comment by ThomasWaldmann** [comment]
@Lassulus can you test current master branch?

should be fixed, but i didn't test with bepasty-cli.

**Comment by ThomasWaldmann** [comment]
0.6.0 was just released!
