### ISSUE TITLE
Recursion Error

### ISSUE THREAD

**Issue by mzch** [bepasty/bepasty-server#211]
When accessing to bepasty, it reported the following error and I wasn't able to get css/js files.

```
[2019-11-12 19:23:24 -0500] [25396] [INFO] Starting gunicorn 20.0.0
[2019-11-12 19:23:24 -0500] [25396] [INFO] Listening at: http://0.0.0.0:9900 (25396)
[2019-11-12 19:23:24 -0500] [25396] [INFO] Using worker: gevent
[2019-11-12 19:23:24 -0500] [25405] [INFO] Booting worker with pid: 25405
[2019-11-12 19:23:24 -0500] [25406] [INFO] Booting worker with pid: 25406
[2019-11-12 19:23:24 -0500] [25407] [INFO] Booting worker with pid: 25407
[2019-11-12 19:23:48 -0500] [25406] [ERROR] Error handling request
Traceback (most recent call last):
  File "/srv/bepasty/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 111, in handle_request
    resp.write_file(respiter)
  File "/srv/bepasty/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/srv/bepasty/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += os.sendfile(sockno, fileno, offset + sent, count)
  File "/srv/bepasty/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  File "/srv/bepasty/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  File "/srv/bepasty/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  [Previous line repeated 967 more times]
RecursionError: maximum recursion depth exceeded
```

Any idea?

**Comment by ThomasWaldmann** [comment]
Which URL did you access?

Your bepasty config (remove any passwords)?

**Comment by ThomasWaldmann** [comment]
In the traceback, there is no bepasty code, so this rather looks like a gunicorn issue.

**Comment by mzch** [comment]
My startup script is below:
```sh
#!/bin/bash

NAME="bepasty"
HOME=/srv/bepasty
PORT=9900  # we will communicate using this unix socket
PIDFILE=$HOME/gunicorn.pid
NUM_WORKERS=3                 # how many worker processes should Gunicorn spawn
export BEPASTY_CONFIG=$HOME/bepasty.conf

source $HOME/bin/activate

cd $HOME/repo

exec gunicorn bepasty.wsgi \
  --name $NAME \
  --workers $NUM_WORKERS \
  --log-level=info \
  --access-logfile $HOME/logs/access.log \
  --error-logfile $HOME/logs/error.log \
  --bind=0.0.0.0:$PORT \
  --pid $PIDFILE \
  -k gevent
```
My bepasty.conf
```
#: name of this site (put YOUR bepasty fqdn here)
SITENAME = 'bunchall.com'

#: base URL path of app (if not served on root URL, but e.g. on http://example.org/bepasty ).
#: setting this to a non-None value will activate the PrefixMiddleware that splits PATH_INFO
#: into SCRIPT_NAME (== APP_BASE_PATH) and the rest of PATH_INFO.
APP_BASE_PATH = None  # '/bepasty'

#: Whether files are automatically locked after upload.
#:
#: If you want to require admin approval and manual unlocking for each
#: uploaded file, set this to True.
UPLOAD_LOCKED = False

#: The site admin can set some maximum allowed file size he wants to
#: accept here. This is the maximum size an uploaded file may have.
MAX_ALLOWED_FILE_SIZE = 5 * 1000 * 1000 * 1000

#: The maximum http request body size.
#: This is an information given to rest api clients so they can adjust
#: their chunk size accordingly.
#:
#: This needs to be in sync with (or at least not beyond) the web server
#: settings:
#: apache:  LimitRequestBody 1048576 # apache default is 0 (unlimited)
#: nginx:  client_max_body_size 1m; # nginx default (== 1048576)
MAX_BODY_SIZE = 1 * 1024 * 1024 - 8192  # 8kiB safety margin, issue #155

#: Setup maximum file sizes for specific content-types. If an item is
#: beyond the limit set for its type, it will not be rendered, but just
#: offered for download. Lookup within MAX_RENDER_SIZE is done by
#: first-match and it is automatically sorted for longer content-type-
#: prefixes first.
#:
#: Format of entries: content-type-prefix: max_size
MAX_RENDER_SIZE = {
    # each list entry has 38 bytes, do not render > 1000 items
    'text/x-bepasty-list': 1000 * 38,
    # stuff rendered with syntax highlighting (expensive for server and
    # client) and also used for other text/* types as we use same code to
    # get a (non-highlighted) display with line numbers:
    'HIGHLIGHT_TYPES': 100 * 1000,
    # the in-browser pdf reader is sometimes rather slow and should
    # rather not be used for big PDFs:
    'application/pdf': 10 * 1000 * 1000,
    'application/x-pdf': 10 * 1000 * 1000,
    # images / audio / video can be rather big, we do not process them:
    'image/': 10 * 1000 * 1000,
    'audio/': 1 * 1000 * 1000 * 1000,
    'video/': 5 * 1000 * 1000 * 1000,
    # DEFAULT - matches everything not matched otherwise.
    # As we have catched everything we are able to render already,
    # this maybe should be a medium size, just for the case we forget
    # something:
    '': 1 * 1000 * 1000,
}

#: Define storage backend, choose from:
#:
#: - 'filesystem'
#:
STORAGE = 'filesystem'

#: Filesystem storage path
STORAGE_FILESYSTEM_DIRECTORY = '/srv/bepasty/storage'

#: server secret key needed for safe session cookies.
#: you must set a very long, very random, very secret string here,
#: otherwise bepasty will not work (and crash when trying to log in)!
SECRET_KEY = '98T6ENdYkYSHQsxjLmuNJUXmt9tHzQdMkETM6wv9Fs3eNPX3sq'

#: transmit cookie only over https (if you use http, set this to False)
SESSION_COOKIE_SECURE = True
#: use a permanent session (True, cookie will expire after the given
#: time, see below) or not (False, cookie will get removed when browser
#: is closed)
PERMANENT_SESSION = False
#: lifetime of the permanent session (in seconds)
PERMANENT_SESSION_LIFETIME = 31 * 24 * 3600

#: Bepasty does **not** use the usual user/password scheme, but **only**
#: uses passwords (or passphrases - we'll call both "a secret" below) as
#: log-in credentials - there are no separate user names.
#:
#: People who log-in using such a secret may get more permissions than
#: those who do not log-in (who just get DEFAULT_PERMISSIONS).
#:
#: Depending on the secret used to log-in, they will get the permissions
#: configured here, see below.
#:
#: You can use same secret / same permissions for all privileged users or
#: set up different secrets / different permissions for each user.
#:
#: If you want to be able to revoke permissions for some user / some group
#: of users, it might be a good idea to remember to whom you gave which
#: secret (and also handle it in a rather fine-grained way).
#:
#: PERMISSIONS is a dict that maps secrets to permissions, use it like:
#:
#: ::
#:
#:     PERMISSIONS = {
#:         'myadminsecret_1.21d-3!wdar34': 'admin,list,create,read,delete',
#:         'uploadersecret_rtghtrbrrrfsd': 'create,read',
#:         'joe_doe_89359299887711335537': 'create,read,delete',
#:     }
PERMISSIONS = {
    # 'foo': 'admin,list,create,read,delete',
}

#: not-logged-in users get these permissions -
#: usually they are either no permissions ('') or read-only ('read').
DEFAULT_PERMISSIONS = ''
```
Well, I don't understand what is wrong...

**Comment by mzch** [comment]
I tried mod_wsgi and uWSGI, and another error occurred.
```
Traceback (most recent call last):
  File "repo/src/bepasty/wsgi.py", line 6, in <module>
    from .app import create_app
ImportError: attempted relative import with no known parent package
unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Comment by ThomasWaldmann** [comment]
This is what I have for uwsgi:
```
paste@web:~/uwsgi$ less conf.yml 
uwsgi:
  socket: /srv/paste/uwsgi/socket
  plugins: python3,logfile
  chdir: /srv/paste
  limit-post: 100000000
  module: bepasty.wsgi:application
  env: BEPASTY_CONFIG=/srv/paste/bepasty.conf
  env: PYTHONHASHSEED=random
  home: /srv/paste/env
  enable-threads: true
  threads: 1
  logger: file:/srv/paste/uwsgi/uwsgi.log
```
bepasty package is installed into `/src/paste/env` virtualenv.

**Comment by mzch** [comment]
Thanks @ThomasWaldmann ! I can run bepasty successfully.

```ini
[uwsgi]

app         = bepasty.wsgi:application
module      = %(app)
http-socket = :9900

env         = BEPASTY_CONFIG=/srv/bepasty/bepasty.conf
home        = /srv/bepasty
enable-threads = true
threads     = 5

logto       = /srv/bepasty/logs/uwsgi.log
loglevel    = info
```

**Comment by Mycah** [comment]
I am experiencing this same issue.  I'm not using virtualenv, but I can't seem to locate a uwsgi anywhere.
@mzch can you explain the location of the config and what you had to change?  Thank you.

**Comment by mzch** [comment]
Hi @Mycah I put config file in APP_ROOT, in my case, /srv/beapsty
