### ISSUE TITLE
readthedocs fails to build 1.1.0 docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [bepasty/bepasty-server#298]
```
Running Sphinx v1.8.6
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/sphinx/builders/latex/__init__.py", line 37, in <module>
    from sphinx.writers.latex import DEFAULT_SETTINGS, LaTeXWriter, LaTeXTranslator
  File "/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/sphinx/writers/latex.py", line 33, in <module>
    from sphinx.util.template import LaTeXRenderer
  File "/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/sphinx/util/template.py", line 17, in <module>
    from sphinx.jinja2glue import SphinxFileSystemLoader
  File "/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/sphinx/jinja2glue.py", line 16, in <module>
    from jinja2 import FileSystemLoader, BaseLoader, TemplateNotFound, \
ImportError: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/jinja2/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/sphinx/application.py", line 224, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/jinja2/__init__.py))

Extension error:
Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/1.1.0/lib/python3.7/site-packages/jinja2/__init__.py))
```

**Comment by ThomasWaldmann** [comment]
Full log: https://readthedocs.org/api/v2/build/19242038.txt

Maybe readthedocs doesn't like Jinja2 3.1.2? Try 3.0.3?

**Comment by ThomasWaldmann** [comment]
Fixed by #299 and #300.

Fixed docs build: https://bepasty-server.readthedocs.io/en/latest/

There is no build for 1.1.0 release, but users can either read the 1.0.0 docs or the latest docs, there aren't big differences at this time.

**Comment by ThomasWaldmann** [comment]
1.2.0 docs now build successfully.
